batch_size: 2
lr: 1e-4
upscale_factor: 4

datapath:
  train:
  - dataset/DIV2K/DIV2K_train_HR
  val:
  - dataset/DIV2K/DIV2K_valid_HR

dm:
  crop_size: 88
  num_workers: 6

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: pl_srgan
  project: pl_srgan
  offline: True

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  logger: ${logger}
  log_every_n_steps: 100
  max_epochs: 1000
  gradient_clip_val: 1000
