datapath:
  train:
  - /home/archimickey/Projects/pl_srgan/dataset/DIV2K/DIV2K_train_HR
  val:
  - /home/archimickey/Projects/pl_srgan/dataset/DIV2K/DIV2K_valid_HR

dm:
  crop_size: 88
  upscale_factor: 4