batch_size: 64
upscale_factor: 4

datapath:
  train:
  - /home/archimickey/Projects/pl_srgan/dataset/DIV2K/DIV2K_train_HR
  val:
  - /home/archimickey/Projects/pl_srgan/dataset/DIV2K/DIV2K_valid_HR

dm:
  crop_size: 88

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: srgan

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  logger: ${logger}
  log_every_n_steps: 100
