batch_size: 64
lr: 1e-5
upscale_factor: 4
name: pl_srgan
ckpt_path: checkpoints/stage_1/stage_1.ckpt


datapath:
  train:
  - dataset/SRGAN/DIV2K/DIV2K_train_HR
  - dataset/SRGAN/Flickr2K
  val:
  - dataset/SRGAN/DIV2K/DIV2K_valid_HR

loss:
  generator_loss:
    scale: 400
  discriminator_loss:
    scale: 2

dm:
  crop_size: 128
  num_workers: 12

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${name}
  project: pl_srgan
  resume: true

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  logger: ${logger}
  log_every_n_steps: 600
  # max_epochs: 10000
  max_steps: 2e5
  gradient_clip_val: 1000
  val_check_interval: 1200
  check_val_every_n_epoch: null
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val/psnr
      save_top_k: 3
      mode: max
      save_last: True
      filename: "srgan_{epoch:02d}"
      verbose: True
    - _target_: pytorch_lightning.callbacks.ModelSummary
      max_depth: 5
