batch_size: 64
lr: 1e-4
upscale_factor: 4
name: pl_srgan

datapath:
  train:
  - dataset/VOC2012/train
  val:
  - dataset/VOC2012/val

loss:
  generator_loss:
    scale: 20
  discriminator_loss:
    scale: 8e6

dm:
  crop_size: 128
  num_workers: 6

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: pl_srgan-wsl
  project: pl_srgan

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  logger: ${logger}
  log_every_n_steps: 500
  max_epochs: 10000
  gradient_clip_val: 1000
  val_check_interval: 1000
  check_val_every_n_epoch: null
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val/psnr_loss
      save_top_k: 3
      mode: min
      dirpath: ${name}/checkpoints
      filename: "srgan_{epoch:02d}"
      verbose: True
    - _target_: pytorch_lightning.callbacks.ModelSummary
      max_depth: 5
